# Import all 4 agents
from agents.bug_detector import detect_bugs
from agents.security_scanner import scan_security
from agents.performance import check_performance
from agents.style_checker import check_style
from services.scoring_service import calculate_score


def run_full_review(changed_files: list) -> dict:
    all_results = []
    
    print(f"\nStarting full review of {len(changed_files)} file(s)...\n")
    
    for file in changed_files:
        filename = file["filename"]
        code = file["code"]
        
        print(f"Reviewing file: {filename}")

        bugs = detect_bugs(code, filename)
        security = scan_security(code, filename)
        performance = check_performance(code, filename)
        style = check_style(code, filename)
        
        file_result = {
            "filename": filename,
            "bug_detection": bugs,
            "security_scan": security,
            "performance_check": performance,
            "style_check": style
        }
        
        all_results.append(file_result)
        print(f"Done reviewing {filename}\n")
    
    print("Full review complete!")

    review_data = {
        "files_reviewed": len(changed_files),
        "results": all_results
    }

    score = calculate_score(review_data)

    review_data["score"] = score
    
    print(f"\nFinal Score: {score['total_score']}/100")
    print(f"Grade: {score['grade']}")
    print(f"Verdict: {score['verdict']}")

    comment = simple_format(review_data)
    review_data["comment"] = comment
    
    return review_data

def simple_format(review_data: dict) -> str:
    score = review_data.get("score", {})
    total = score.get("total_score", 0)
    grade = score.get("grade", "N/A")
    verdict = score.get("verdict", "N/A")

    comment = f"""CodeReview AI Report

 Score: {total}/100 | Grade: {grade}
{verdict}

---

"""
    
    for file_result in review_data.get("results", []):
        filename = file_result.get("filename", "unknown")
        comment += f"`{filename}`\n\n"
        agents = [
            ("bug_detection",     "Bugs"),
            ("security_scan",     "Security"),
            ("performance_check", "Performance"),
            ("style_check",       "Style"),
        ]
        
        for agent_key, agent_title in agents:
            agent_result = file_result.get(agent_key, {})
            issues = agent_result.get("issues", [])
            
            comment += f"{agent_title}\n"
            
            # If no issues found
            if not issues:
                comment += "No issues found!\n\n"
                
            else:
                for issue in issues:
                    severity = issue.get("severity", "low").upper()
                    problem = issue.get("problem", "")
                    fix = issue.get("fix", "")
                    
                    comment += f"[{severity}] {problem}\n"
                    comment += f"   > Fix: {fix}\n\n"
    
    comment += "\n*Generated by CodeReview AI*"
    
    return comment